### ISSUE TITLE
8comic has changed their domain name

### ISSUE THREAD

**Issue by lcy0321** [zeroshine/ComicsScroller#1]
8comic has changed their domain name from "8comic.com" to "comicvip.com",
so that this addon is not available on 8comic.

8comic的網址已改為「www.comicvip.com」，
此套件對其失效。

**Comment by zeroshine** [comment]
fix it

**Comment by lcy0321** [comment]
Still not work on firefox.
It seems that it direct to "www.new.comicvip.com"

**Comment by zeroshine** [comment]
Firefox version needs a huge modification on architecture. 
So if it's possible just use the chrome version for now.
I will fix firefox version ASAP.

**Comment by lcy0321** [comment]
感謝回覆，
我將所有.js檔中有關「new.comic.com」的字串及正規表示句改為「www.comic.com」後，
目前運作正常，
提供您作參考，
謝謝。
