### ISSUE TITLE
是否仍然支援 Firefox?

### ISSUE THREAD

**Issue by kevinptt0323** [zeroshine/ComicsScroller#10]
在網站中有給上 firefox xpi 的連結，然而已經失效。請問目前是否支援 firefox？

**Comment by zeroshine** [comment]
目前暫時沒有支援 firefox 的計畫 但是歡迎 PR

**Comment by kidwm** [comment]
現在有 WebExtension 可以直接移植

**Comment by zeroshine** [comment]
之前其實有常試過 web extension 在一些 extension host 的頁面 csp 機制有點問題，就沒有認真去解了
