### ISSUE TITLE
DM5 的支援好像壞了

### ISSUE THREAD

**Issue by markwu** [zeroshine/ComicsScroller#11]
可能是 DM5 改版了，所以造成只顯示前面幾頁漫畫。

**Comment by zeroshine** [comment]
@markwu 
可以提供漫畫章節網址嘛 讓我檢查一下

**Comment by markwu** [comment]
我看了幾本漫畫都會這樣，像是海賊王 

http://www.dm5.com/manhua-haizeiwang-onepiece/

**Comment by zeroshine** [comment]
可以給哪一個章節方便檢查嘛

**Comment by markwu** [comment]
我試了一下還是一樣，例如：

chrome-extension://mccpalfmlnjadfnojmphffidnbemnkec/app.html?site=dm5&chapter=m4761

他只顯示了，前面 7 頁，再往下 scroll 就都是空空的。

**Comment by markwu** [comment]
只顯示了前面七頁，往下都是空的。

![2017-05-18 11 00 53](https://cloud.githubusercontent.com/assets/196861/26208915/ea2a3442-3c1d-11e7-93f4-1ca4b03f83e5.png)

**Comment by markwu** [comment]
OK，我找到原因了。

不知道是什麼原因，我必須 reset config，reset config 之後，就一切正常了。

**Comment by SportsmanLee** [comment]
好像不只一個人有這問題..

我認識的2個朋友第一次裝都會這樣

不過reset config就好了。

**Comment by zeroshine** [comment]
Sorry 我發現問題了 我會儘快修好他
