### ISSUE TITLE
在 Chrome 無痕模式下無法使用

### ISSUE THREAD

**Issue by markwu** [zeroshine/ComicsScroller#12]
在 Chrome 無痕模式下無法使用，會顯示這個擴充功能遭到封鎖。

![2017-05-18 1 37 30](https://cloud.githubusercontent.com/assets/196861/26167869/ad66180e-3b6a-11e7-8c98-599a38ab7b28.png)

**Comment by zeroshine** [comment]
ComicsScroller 不會支援無痕模式喔

**Comment by markwu** [comment]
OK，那我把這個 issue close 了。
