### ISSUE TITLE
無法往回捲動

### ISSUE THREAD

**Issue by markwu** [zeroshine/ComicsScroller#13]
看 Dm5 下的漫畫，一開始看沒問題。但是要往回捲動時，發現會卡住一直重複跳到上一張圖的位置，無法往回捲動。

**Comment by markwu** [comment]
這是剛剛錄下來的，請看。

我一開始快速地向下捲動，然後是的往回捲動，結果一直跳到重複的位置，無法往回捲動。

[Screenshot](http://i.imgur.com/EkRJR3S.gifv)

**Comment by zeroshine** [comment]
收到 我也reproduce了 我會在找時間debug

**Comment by zeroshine** [comment]
我在這個 commit 修正了 也 release 4.0.13 最新版本了 看能不能幫忙測試一下 感恩
76cf88c08e65a5c4816cc079bc7561c0ab5bcbe9

**Comment by markwu** [comment]
抱歉，前幾天比較忙，沒有幫忙看。感謝你，確認修復。
