### ISSUE TITLE
載入大圖的時候圖片左右2邊會被切割??

### ISSUE THREAD

**Issue by aa66609** [zeroshine/ComicsScroller#15]
原圖看的話沒問題(使用開啟新頁面圖片)
可是如果用閱讀器看的話左右2邊會被切割(基本上只有2頁合併的那種大圖會出現這問題)
請問有人有這個問題嗎?

**Comment by aa66609** [comment]
補充一點，是在縮放網頁大小時 如果比例是100%就沒有這問題

**Comment by JJcdomat** [comment]
我的是100%视图的时候显示不全。而使用缩放，比如缩放到80%就可以了。

**Comment by zeroshine** [comment]
4.0.17版本應該解掉了

**Comment by JJcdomat** [comment]
现在则是会导致字体太小看不清。我是在看dm5的漫画发现这个问题的。我到原网页查看的时候原网页也是会两边显示不全，所以应该是网站方面处理不好吧。

**Comment by zeroshine** [comment]
可以截個圖看一下嘛

**Comment by JJcdomat** [comment]
缩放前
![缩放前](https://upload.cc/i/qJHjQN.png)
110%缩放
![110%缩放](https://upload.cc/i/iYe238.png)
当然也可能是我的分辨率太低。
