### ISSUE TITLE
漫畫頁面加上回到原網站的超連結

### ISSUE THREAD

**Issue by Jasonnor** [zeroshine/ComicsScroller#17]
有時看到一半想回去原漫畫網站瀏覽評論或去找其他漫畫，發現沒有地方能點

不知道可否增加這個功能 😅

例如放在這邊：![image](https://user-images.githubusercontent.com/7609173/26882573-59926b9c-4bcd-11e7-8ed3-16d787ba43a5.png)

**Comment by SportsmanLee** [comment]
其實好像已經有這個功能了說..
![image](https://user-images.githubusercontent.com/2972583/26883858-e7e00c9e-4bd0-11e7-92b3-6d9e52d0bacb.png)

**Comment by zeroshine** [comment]
最新版本加進去了
