### ISSUE TITLE
動漫屋 好像被擋掉了

### ISSUE THREAD

**Issue by derty0304** [zeroshine/ComicsScroller#18]
不能在動漫屋上使用

**Comment by zeroshine** [comment]
可以提供網址 截圖 更多的資訊嘛 我自己是可以用

**Comment by derty0304** [comment]
抱歉!!
好像是因為我裝了 ublock 導致與您的擴充套件有衝突
目前關掉 ublock 可以正常瀏覽

**Comment by zeroshine** [comment]
我自己用 ublock origin 是可以相容的 也許你可以檢查一下你的黑名單
