### ISSUE TITLE
dm5 4:3 圖片過小?

### ISSUE THREAD

**Issue by SportsmanLee** [zeroshine/ComicsScroller#19]
hi,  今天在dm5看七原罪 224話時
有一張橫圖(約4:3)在comicscroller上的呈現被縮小蠻多的
如下圖:
![default](https://user-images.githubusercontent.com/2972583/27828145-4a7171f0-60ed-11e7-9f13-3c7d4e003536.PNG)
而原圖應該是蠻大的

想請問有辦法讓這類橫圖呈現的比例大小跟一般直圖差不多嗎?
Thank you.

**Comment by zeroshine** [comment]
重新整理看看呢？

**Comment by SportsmanLee** [comment]
換一台電腦後就沒問題了..

明天到公司再試試看@@
沒問題就可以關掉issue了

感謝
