### ISSUE TITLE
View in http://www.dm5.com is not working

### ISSUE THREAD

**Issue by rexyeah** [zeroshine/ComicsScroller#21]
Hello,
Seems this extension has been blocked by http://www.dm5.com

**Comment by SportsmanLee** [comment]
It seems only not working on adult comics like: http://www.dm5.com/manhua-jianyuxueyuan/

**Comment by SportsmanLee** [comment]
It seems not working only on adult comics like: http://www.dm5.com/manhua-jianyuxueyuan/

And this one is fine: http://www.dm5.com/manhua-migongfan

**Comment by zeroshine** [comment]
Can you provide os and chrome version and which chapter url can not be seen?
Because I could not reproduce, even if the adult comics

**Comment by SportsmanLee** [comment]
說來奇怪，我這邊也reproduce不出來了@@

**Comment by rexyeah** [comment]
Seems it's not reproducible again for now.
I'm going to close this issue. Thanks for your promptly response.
