### ISSUE TITLE
View in http://www.dm5.com/ has been blocked

### ISSUE THREAD

**Issue by SportsmanLee** [zeroshine/ComicsScroller#23]
Hi,

又可以reproduce了~
這次持續比較久，從昨晚到現在..

Repro step:
1. browse http://www.dm5.com/m515445/ with ComcsScroller.

Result:
![image](https://user-images.githubusercontent.com/2972583/29203237-204a7aa2-7ea2-11e7-9a4a-c5f083782892.png)

Expect Result:
Can browse normally

大大有空可以檢查一下，感恩~

**Comment by zeroshine** [comment]
有，剛剛修掉了，感謝回報
