### ISSUE TITLE
暫時修正comicbus圖片的抓取

### ISSUE THREAD

**Issue by seansg** [zeroshine/ComicsScroller#26]
hi @zeroshine 
我有改了一個branch 
暫時可以正常讀取 comicbus 的網站
但是沒有權限可以發 PR
如果需要可以再跟我說

**Comment by zeroshine** [comment]
我沒有鎖權限欸 你發看看

**Comment by seansg** [comment]
無法push new branch
他說沒有權限

**Comment by seansg** [comment]
好像可以了？
