### ISSUE TITLE
通知失效?

### ISSUE THREAD

**Issue by tw0517tw** [zeroshine/ComicsScroller#32]
即使有更新也不會出現在 update 分頁

**Comment by zeroshine** [comment]
這功能暫時被我拿掉，因為動漫屋大改版，我怕會造成通知大爆炸，所以暫時性的把這個功能拿掉，等章節都更新了以後下一個版本會打開，應該最近就會把這個功能打開

**Comment by tw0517tw** [comment]
感謝，先 close 了
