### ISSUE TITLE
SF Comic 失效

### ISSUE THREAD

**Issue by williesmithchen** [zeroshine/ComicsScroller#5]
![image](https://cloud.githubusercontent.com/assets/4962190/15011614/6be306a4-1225-11e6-9ea2-c35c2fb90ddc.png)

**Comment by zeroshine** [comment]
SF的圖床隨機會壞掉 修不了QQ

**Comment by williesmithchen** [comment]
(sad)

**Comment by kidwm** [comment]
@zeroshine 加上 HTTP Header Referer 就行了, 例如：
Referer: `http://comic.sfacg.com/HTML/OnePiece/825/`

**Comment by zeroshine** [comment]
@kidwm 我之前試過好像還是沒用 我在試試看...

**Comment by zeroshine** [comment]
@kidwm 之前試過 referer 有些好像還是爛掉 現在可以了

**Comment by williesmithchen** [comment]
Fixed #b1ed7168514ea89cab553a9759cd778523f2baba

**Comment by kidwm** [comment]
@zeroshine 應該是 Chrome 的 cache ，不是真的爛掉
