### ISSUE TITLE
關於Firefox安裝的問題

### ISSUE THREAD

**Issue by Pixmi** [zeroshine/ComicsScroller#9]
我參考了這篇讓Firefox可以安裝chrome extensions的文章
http://www.ghacks.net/2016/05/23/install-google-chrome-extensions-firefox/

為了正常安裝，從chrome store取得的extensions必須通過mozilla的AMO簽證

但在簽證的過程中出了錯誤
http://pixmi.net/image/ComicsScroller-error.png

如果這問題修正，就可以推廣Firefox使用者改成透過這方式安裝ComicsScroller

**Comment by zeroshine** [comment]
先謝謝回報這個 firefox 的部份
先前是因為 firefox 有很嚴格的 policy 不希望使用 eval 
然而 comicsScroller 要破解 dm5 有用到 eval
所以審核就不能通過

現在不曉得 firefox 有沒有開放 chrome extension 中的 content security policy unsafe-eval 的部份
能不能直接搬過去我是持保留態度也沒有開始研究(汗
另外我已經有在緩慢的著手重構程式碼 目前希望會慢慢的先更新 chrome 的部份
有餘力會在考慮維護 firefox 的版本

感謝

**Comment by ClioneSonar** [comment]
或許不用特地開發Firefox版本唷
Firefox未來的發展方向，將改用WebExtensions作為開發套件的標準
WebExtensions是基於相容chrome來設計的，具體參考這邊
https://developer.mozilla.org/zh-TW/Add-ons/WebExtensions

之後chrome版本只要小幅更新就可以套用在Firefox的新標準上了

**Comment by zeroshine** [comment]
是的 我了解這個部分
當初停止開發 firefox addon 的原因 就是因為 firefox 開始依照 chrome extension api 發展 webextension 想說以後可能只需要維護一個版本就夠了
但是因為上班以後沒有什麼時間仔細去研究這個部分 所以就先維穩為主 目前研究 webextension 的 priority排在重構專案的後面 希望有空可以慢慢做好這些部分
